[data]
data=./data/processed/Performance/
sensors_distance=./data/Performance/Performance.csv
seed=10
column_wise=False
normalizer=std
batch_size=64

[model]
num_of_vertices=5011
construct_type=connectivity
in_dim=1
hidden_dims=[[64],[64],[64]]
first_layer_embedding_size=64
out_layer_dim=128
history=4
horizon=2
strides=2
temporal_emb=True
spatial_emb=True
use_mask=True
activation=GLU

[train]
seed=10
learning_rate=0.001
lr_decay=False
lr_decay_step=20,40
lr_decay_rate=0.3
epochs=1
print_every=100
save=./garage/Performance/
expid=1
max_grad_norm=5.0
patience=20
log_file=./result/Performance/log_Performance

[test]
log_file=./result/Performance/log_test_Performance
